"""empty message

Revision ID: 8a4adac7a819
Revises: c863348b097a
Create Date: 2022-01-27 16:55:00.453770

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8a4adac7a819'
down_revision = 'c863348b097a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_joined_at'), 'user', ['joined_at'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('website', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_comment'), 'comments', ['comment'], unique=False)
    op.create_index(op.f('ix_comments_created_on'), 'comments', ['created_on'], unique=False)
    op.create_index(op.f('ix_comments_email'), 'comments', ['email'], unique=False)
    op.create_index(op.f('ix_comments_website'), 'comments', ['website'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_website'), table_name='comments')
    op.drop_index(op.f('ix_comments_email'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_on'), table_name='comments')
    op.drop_index(op.f('ix_comments_comment'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_joined_at'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
