"""empty message

Revision ID: d9cb921e6446
Revises: 
Create Date: 2022-02-05 10:24:13.477897

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd9cb921e6446'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=500), nullable=True),
    sa.Column('category_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('blog_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_category_category'), ['category'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_joined_at'), ['joined_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('blog_description', sa.String(length=500), nullable=True),
    sa.Column('slug', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=500), nullable=True),
    sa.Column('modified_by', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_blog_description'), ['blog_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_created_on'), ['created_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_image_url'), ['image_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_modified_by'), ['modified_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_title'), ['title'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('website', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_comment'), ['comment'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_created_on'), ['created_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_website'), ['website'], unique=False)

    op.create_table('blog_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog'], ['blog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_comments_created_datetime'), ['created_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_comments_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_comments_name'), ['name'], unique=False)

    op.create_table('category_identifier',
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('blog_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_category_id'], ['blog_category.id'], ),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_identifier')
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_comments_name'))
        batch_op.drop_index(batch_op.f('ix_blog_comments_email'))
        batch_op.drop_index(batch_op.f('ix_blog_comments_created_datetime'))

    op.drop_table('blog_comments')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_website'))
        batch_op.drop_index(batch_op.f('ix_comments_email'))
        batch_op.drop_index(batch_op.f('ix_comments_created_on'))
        batch_op.drop_index(batch_op.f('ix_comments_comment'))

    op.drop_table('comments')
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_title'))
        batch_op.drop_index(batch_op.f('ix_blog_slug'))
        batch_op.drop_index(batch_op.f('ix_blog_modified_by'))
        batch_op.drop_index(batch_op.f('ix_blog_image_url'))
        batch_op.drop_index(batch_op.f('ix_blog_created_on'))
        batch_op.drop_index(batch_op.f('ix_blog_created_by'))
        batch_op.drop_index(batch_op.f('ix_blog_blog_description'))
        batch_op.drop_index(batch_op.f('ix_blog_author'))

    op.drop_table('blog')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_joined_at'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('blog_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_category_category'))

    op.drop_table('blog_category')
    # ### end Alembic commands ###
